In [11]:
import pandas as pd
import numpy as np
from peewee_models import *

In [12]:

# Transformación y concatenación de los csv anteriormente generados a un solo dataframe para ingestarlos después a la base de datos

wpp_poblacion = pd.read_csv("../datasets/sql/world_population_prospects/wpp_poblacion.csv")
wdi_poblacion = pd.read_csv("../datasets/sql/world_development_indicators/wdi_poblacion.csv")
wpp_poblacion.set_index(["region_id", "year"], inplace=True)
wdi_poblacion.set_index(["region_id", "year"], inplace=True)
table_poblacion = wpp_poblacion.merge(wdi_poblacion, how="right", left_index=True, right_index=True).drop(['id_x','name_x','id_y','name_y'],axis=1).reset_index()
table_poblacion = table_poblacion[table_poblacion['region_id'].notna()]
table_poblacion = table_poblacion.replace(np.nan, None)
table_poblacion.region_id = table_poblacion.region_id.astype(int)

wpp_salud = pd.read_csv("../datasets/sql/world_population_prospects/wpp_salud.csv")
wdi_salud = pd.read_csv("../datasets/sql/world_development_indicators/wdi_salud.csv")
wpp_salud.set_index(["region_id", "year"], inplace=True)
wdi_salud.set_index(["region_id", "year"], inplace=True)
table_salud = wpp_salud.merge(wdi_salud, how="right", left_index=True, right_index=True).drop(['id_x','name_x','id_y','name_y'],axis=1).reset_index()
table_salud = table_salud[table_salud['region_id'].notna()]
table_salud = table_salud.replace(np.nan, None)
table_salud.region_id = table_salud.region_id.astype(int)

wdi_economia = pd.read_csv("../datasets/sql/world_development_indicators/wdi_economia.csv").drop(['id','name'],axis=1)
table_economia = wdi_economia
table_economia = table_economia.replace(np.nan, None)

wdi_educacion = pd.read_csv("../datasets/sql/world_development_indicators/wdi_educacion.csv").drop(['id','name'],axis=1)
table_educacion = wdi_educacion
table_educacion = table_educacion.replace(np.nan, None)

wdi_empleos = pd.read_csv("../datasets/sql/world_development_indicators/wdi_empleos.csv").drop(['id','name'],axis=1)
table_empleos = wdi_empleos
table_empleos = table_empleos.replace(np.nan, None)

In [16]:
table_poblacion = table_poblacion.set_index('region_id')

In [15]:
table_poblacion.columns

Index(['region_id', 'year', 'median_age_as_1_july_years',
       'net_migration_rate_per_1000_population',
       'net_number_migrants_thousands', 'fem_population_as_1_july_thousands',
       'male_population_as_1_july_thousands',
       'urban_population_growth_annual_prcnt',
       'rural_population_growth_annual_prcnt',
       'international_migrant_stock_total', 'population_growth_annual_prcnt',
       'population_in_largest_city'],
      dtype='object')

In [71]:
len(table_poblacion)

4836

In [80]:
Demography.insert(table_poblacion.iloc[4000:5000].to_dict(orient='records')).execute()

IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`henrytest`.`demography`, CONSTRAINT `demography_ibfk_1` FOREIGN KEY (`region_id`) REFERENCES `region` (`id`))')

In [73]:
with database.atomic():
    for idx in range(0, len(table_economia), 100):
        Demography.insert(table_poblacion.iloc[idx:idx+100].to_dict(orient='records')).execute()

IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`henrytest`.`demography`, CONSTRAINT `demography_ibfk_1` FOREIGN KEY (`region_id`) REFERENCES `region` (`id`))')

In [72]:
table_poblacion.iloc[51:4900]

,region_id,year,median_age_as_1_july_years,net_migration_rate_per_1000_population,net_number_migrants_thousands,fem_population_as_1_july_thousands,male_population_as_1_july_thousands,urban_population_growth_annual_prcnt,rural_population_growth_annual_prcnt,international_migrant_stock_total,population_growth_annual_prcnt,population_in_largest_city
51,2,2010,14.404,-5.001,-141.355,13949.295,14240.377,3.779279,2.621229,102246.0,2.894904,3289005.0
52,2,2011,14.679,14.42,418.796,14468.875,14780.282,4.574493,3.412449,0.0,3.689508,3371653.0
53,2,2012,15.011,3.481,105.905,15067.373,15399.105,4.958981,3.798483,0.0,4.077628,3456496.0
54,2,2013,15.239,1.525,48.076,15594.637,15946.572,4.344553,3.185537,0.0,3.466788,3543232.0
55,2,2014,15.501,7.842,255.611,16172.321,16543.889,4.531769,3.374206,0.0,3.657576,3632269.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4831,179,2016,46.316,1.237,156.993,65203.529,61790.329,0.031996,-0.936820,0.0,-0.051137,37326706.0
4832,179,2017,46.721,1.296,164.07,65047.99,61614.482,0.003375,-0.999097,0.0,-0.081874,37397437.0
4833,179,2018,47.139,1.407,177.47,64855.455,61400.411,-0.038428,-1.088373,0.0,-0.126880,37468302.0
4834,179,2019,47.572,1.464,183.953,64633.006,61158.671,-0.051001,-1.123327,0.0,-0.140465,37435191.0
4835,179,2020,47.983,0.7,87.584,64363.155,60881.605,-0.202631,-1.311156,0.0,-0.294195,37393129.0

In [82]:
table_poblacion.region_id.unique()

array([  1,   2,   3,   4,   5,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  25,  26,  27,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  77,  78,  80,  82,  83,  84,  85,
        86,  87,  88,  90,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 107, 108, 109, 110, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 140, 141, 142, 143, 145, 146,
       147, 148, 149, 150, 151, 152, 153, 154, 155, 158, 159, 160, 161,
       162, 163, 164, 166, 167, 168, 169, 170, 171, 172, 173, 174, 179],
      dtype=int64)

In [67]:
table_poblacion.iloc[21:50].to_dict(orient='records')

[{'region_id': 1,
  'year': 2010,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 3.24435486033937,
  'rural_population_growth_annual_prcnt': 0.130510680872939,
  'international_migrant_stock_total': 61756.0,
  'population_growth_annual_prcnt': 1.06742976658398,
  'population_in_largest_city': 6189370.0},
 {'region_id': 1,
  'year': 2011,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 3.22377949288483,
  'rural_population_growth_annual_prcnt': 0.110106197857633,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 1.06749342269972,
  'population_in_largest_city': 6405520.0},
 {'region_id': 1,
  'year': 2012,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 3.21113051981827,
  'rural_population_growth_annual_prcnt': 0.0921857852165925,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 1.07201322213276,
  'population_in_largest_city': 6629220.0},
 {'region_id': 1,
  'year': 2013,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 3.18611624041608,
  'rural_population_growth_annual_prcnt': 0.0794563433893053,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 1.07637953190022,
  'population_in_largest_city': 6860731.0},
 {'region_id': 1,
  'year': 2014,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 3.15972531846692,
  'rural_population_growth_annual_prcnt': 0.0459818614226579,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 1.06639876535975,
  'population_in_largest_city': 7100328.0},
 {'region_id': 1,
  'year': 2015,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 3.11634097364234,
  'rural_population_growth_annual_prcnt': -0.000752179877512,
  'international_migrant_stock_total': 72793.0,
  'population_growth_annual_prcnt': 1.04227094610537,
  'population_in_largest_city': 7348291.0},
 {'region_id': 1,
  'year': 2016,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 3.06143512628087,
  'rural_population_growth_annual_prcnt': -0.0554769793457835,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 1.00922663268309,
  'population_in_largest_city': 7604915.0},
 {'region_id': 1,
  'year': 2017,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 2.98533941955856,
  'rural_population_growth_annual_prcnt': -0.110529312209638,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 0.968719959338428,
  'population_in_largest_city': 7870501.0},
 {'region_id': 1,
  'year': 2018,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 2.91794712714328,
  'rural_population_growth_annual_prcnt': -0.162865748391567,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 0.932840031984421,
  'population_in_largest_city': 8145361.0},
 {'region_id': 1,
  'year': 2019,
  'median_age_as_1_july_years': None,
  'net_migration_rate_per_1000_population': None,
  'net_number_migrants_thousands': None,
  'fem_population_as_1_july_thousands': None,
  'male_population_as_1_july_thousands': None,
  'urban_population_growth_annual_prcnt': 2.85915028568362,
  'rural_population_growth_annual_prcnt': -0.208088327468402,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 0.904491214904611,
  'population_in_largest_city': 8371428.0},
 {'region_id': 2,
  'year': 1990,
  'median_age_as_1_july_years': 15.092,
  'net_migration_rate_per_1000_population': -60.375,
  'net_number_migrants_thousands': -666.001,
  'fem_population_as_1_july_thousands': 5346.409,
  'male_population_as_1_july_thousands': 5348.387,
  'urban_population_growth_annual_prcnt': 0.623574329460614,
  'rural_population_growth_annual_prcnt': 0.0895897841415977,
  'international_migrant_stock_total': 57686.0,
  'population_growth_annual_prcnt': 0.202433955671883,
  'population_in_largest_city': 1549320.0},
 {'region_id': 2,
  'year': 1991,
  'median_age_as_1_july_years': 15.022,
  'net_migration_rate_per_1000_population': 3.721,
  'net_number_migrants_thousands': 39.926,
  'fem_population_as_1_july_thousands': 5372.208,
  'male_population_as_1_july_thousands': 5372.959,
  'urban_population_growth_annual_prcnt': 0.889255391381243,
  'rural_population_growth_annual_prcnt': 0.356908545974853,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 0.469880406765633,
  'population_in_largest_city': 1618697.0},
 {'region_id': 2,
  'year': 1992,
  'median_age_as_1_july_years': 14.947,
  'net_migration_rate_per_1000_population': 164.629,
  'net_number_migrants_thousands': 1834.556,
  'fem_population_as_1_july_thousands': 6028.939,
  'male_population_as_1_july_thousands': 6028.494,
  'urban_population_growth_annual_prcnt': 11.9401759977564,
  'rural_population_growth_annual_prcnt': 11.409417178063,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 11.5225244151801,
  'population_in_largest_city': 1691283.0},
 {'region_id': 2,
  'year': 1993,
  'median_age_as_1_july_years': 14.874,
  'net_migration_rate_per_1000_population': 87.304,
  'net_number_migrants_thousands': 1171.818,
  'fem_population_as_1_july_thousands': 7000.119,
  'male_population_as_1_july_thousands': 7003.641,
  'urban_population_growth_annual_prcnt': 15.3803361368896,
  'rural_population_growth_annual_prcnt': 14.8512286351699,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 14.9644548746872,
  'population_in_largest_city': 1766910.0},
 {'region_id': 2,
  'year': 1994,
  'median_age_as_1_july_years': 14.784,
  'net_migration_rate_per_1000_population': 43.986,
  'net_number_migrants_thousands': 665.41,
  'fem_population_as_1_july_thousands': 7722.096,
  'male_population_as_1_july_thousands': 7733.458,
  'urban_population_growth_annual_prcnt': 10.2830849918572,
  'rural_population_growth_annual_prcnt': 9.74962752147243,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 9.86426206628341,
  'population_in_largest_city': 1846031.0},
 {'region_id': 2,
  'year': 1995,
  'median_age_as_1_july_years': 14.681,
  'net_migration_rate_per_1000_population': 4.383,
  'net_number_migrants_thousands': 71.824,
  'fem_population_as_1_july_thousands': 8199.445,
  'male_population_as_1_july_thousands': 8219.467,
  'urban_population_growth_annual_prcnt': 6.46362794435513,
  'rural_population_growth_annual_prcnt': 5.93176495442201,
  'international_migrant_stock_total': 71522.0,
  'population_growth_annual_prcnt': 6.04653555233991,
  'population_in_largest_city': 1928694.0},
 {'region_id': 2,
  'year': 1996,
  'median_age_as_1_july_years': 14.57,
  'net_migration_rate_per_1000_population': 1.59,
  'net_number_migrants_thousands': 27.194,
  'fem_population_as_1_july_thousands': 8537.421,
  'male_population_as_1_july_thousands': 8569.175,
  'urban_population_growth_annual_prcnt': 4.51834828935036,
  'rural_population_growth_annual_prcnt': 3.98812892930806,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 4.1030220499493,
  'population_in_largest_city': 2015181.0},
 {'region_id': 2,
  'year': 1997,
  'median_age_as_1_july_years': 14.453,
  'net_migration_rate_per_1000_population': 0.345,
  'net_number_migrants_thousands': 6.129,
  'fem_population_as_1_july_thousands': 8871.958,
  'male_population_as_1_july_thousands': 8916.862,
  'urban_population_growth_annual_prcnt': 4.32881543850933,
  'rural_population_growth_annual_prcnt': 3.79429674749808,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 3.9106052193522,
  'population_in_largest_city': 2105292.0},
 {'region_id': 2,
  'year': 1998,
  'median_age_as_1_july_years': 14.333,
  'net_migration_rate_per_1000_population': 1.934,
  'net_number_migrants_thousands': 35.74,
  'fem_population_as_1_july_thousands': 9217.591,
  'male_population_as_1_july_thousands': 9275.541,
  'urban_population_growth_annual_prcnt': 4.29482385236621,
  'rural_population_growth_annual_prcnt': 3.76776930745852,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 3.88293060489748,
  'population_in_largest_city': 2199565.0},
 {'region_id': 2,
  'year': 1999,
  'median_age_as_1_july_years': 14.221,
  'net_migration_rate_per_1000_population': 4.461,
  'net_number_migrants_thousands': 85.758,
  'fem_population_as_1_july_thousands': 9595.036,
  'male_population_as_1_july_thousands': 9667.811,
  'urban_population_growth_annual_prcnt': 4.49265521188791,
  'rural_population_growth_annual_prcnt': 3.96129694067396,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 4.07787948472197,
  'population_in_largest_city': 2298059.0},
 {'region_id': 2,
  'year': 2000,
  'median_age_as_1_july_years': 14.127,
  'net_migration_rate_per_1000_population': -50.229,
  'net_number_migrants_thousands': -1007.135,
  'fem_population_as_1_july_thousands': 9727.541,
  'male_population_as_1_july_thousands': 9815.442,
  'urban_population_growth_annual_prcnt': 1.86137729962901,
  'rural_population_growth_annual_prcnt': 1.32580608474027,
  'international_migrant_stock_total': 75917.0,
  'population_growth_annual_prcnt': 1.4438030241194,
  'population_in_largest_city': 2401109.0},
 {'region_id': 2,
  'year': 2001,
  'median_age_as_1_july_years': 14.059,
  'net_migration_rate_per_1000_population': -9.717,
  'net_number_migrants_thousands': -192.286,
  'fem_population_as_1_july_thousands': 9793.166,
  'male_population_as_1_july_thousands': 9895.467,
  'urban_population_growth_annual_prcnt': 1.15383861520503,
  'rural_population_growth_annual_prcnt': 0.625666867583049,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 0.742516834396313,
  'population_in_largest_city': 2508477.0},
 {'region_id': 2,
  'year': 2002,
  'median_age_as_1_july_years': 14.025,
  'net_migration_rate_per_1000_population': 65.242,
  'net_number_migrants_thousands': 1327.074,
  'fem_population_as_1_july_thousands': 10438.055,
  'male_population_as_1_july_thousands': 10562.202,
  'urban_population_growth_annual_prcnt': 6.86345297807244,
  'rural_population_growth_annual_prcnt': 6.33104778193872,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 6.44932147797304,
  'population_in_largest_city': 2620804.0},
 {'region_id': 2,
  'year': 2003,
  'median_age_as_1_july_years': 14.017,
  'net_migration_rate_per_1000_population': 17.307,
  'net_number_migrants_thousands': 388.632,
  'fem_population_as_1_july_thousands': 11247.647,
  'male_population_as_1_july_thousands': 11397.483,
  'urban_population_growth_annual_prcnt': 7.95344768841497,
  'rural_population_growth_annual_prcnt': 7.42260371898086,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 7.54101896480183,
  'population_in_largest_city': 2738161.0},
 {'region_id': 2,
  'year': 2004,
  'median_age_as_1_july_years': 14.033,
  'net_migration_rate_per_1000_population': -10.498,
  'net_number_migrants_thousands': -248.616,
  'fem_population_as_1_july_thousands': 11690.825,
  'male_population_as_1_july_thousands': 11862.726,
  'urban_population_growth_annual_prcnt': 4.58865325754718,
  'rural_population_growth_annual_prcnt': 3.74368031073764,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 3.93317768847308,
  'population_in_largest_city': 2834061.0},
 {'region_id': 2,
  'year': 2005,
  'median_age_as_1_july_years': 14.164,
  'net_migration_rate_per_1000_population': 10.383,
  'net_number_migrants_thousands': 252.185,
  'fem_population_as_1_july_thousands': 12109.086,
  'male_population_as_1_july_thousands': 12302.104,
  'urban_population_growth_annual_prcnt': 4.47468958963317,
  'rural_population_growth_annual_prcnt': 3.31422737698589,
  'international_migrant_stock_total': 87300.0,
  'population_growth_annual_prcnt': 3.57650800354462,
  'population_in_largest_city': 2905178.0},
 {'region_id': 2,
  'year': 2006,
  'median_age_as_1_july_years': 14.326,
  'net_migration_rate_per_1000_population': 2.466,
  'net_number_migrants_thousands': 62.684,
  'fem_population_as_1_july_thousands': 12614.497,
  'male_population_as_1_july_thousands': 12828.447,
  'urban_population_growth_annual_prcnt': 5.03421600301046,
  'rural_population_growth_annual_prcnt': 3.87541461793337,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 4.13967803534352,
  'population_in_largest_city': 2978181.0},
 {'region_id': 2,
  'year': 2007,
  'median_age_as_1_july_years': 14.125,
  'net_migration_rate_per_1000_population': -35.743,
  'net_number_migrants_thousands': -942.887,
  'fem_population_as_1_july_thousands': 12835.34,
  'male_population_as_1_july_thousands': 13067.961,
  'urban_population_growth_annual_prcnt': 2.68846842633562,
  'rural_population_growth_annual_prcnt': 1.5256272228491,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 1.79319572747206,
  'population_in_largest_city': 3053018.0},
 {'region_id': 2,
  'year': 2008,
  'median_age_as_1_july_years': 14.044,
  'net_migration_rate_per_1000_population': 8.401,
  'net_number_migrants_thousands': 221.0,
  'fem_population_as_1_july_thousands': 13088.192,
  'male_population_as_1_july_thousands': 13339.006,
  'urban_population_growth_annual_prcnt': 2.89394890008399,
  'rural_population_growth_annual_prcnt': 1.73274317628769,
  'international_migrant_stock_total': 0.0,
  'population_growth_annual_prcnt': 2.00233326232255,
  'population_in_largest_city': 3129844.0}]

In [49]:
table_poblacion

,region_id,year,median_age_as_1_july_years,net_migration_rate_per_1000_population,net_number_migrants_thousands,fem_population_as_1_july_thousands,male_population_as_1_july_thousands,urban_population_growth_annual_prcnt,rural_population_growth_annual_prcnt,international_migrant_stock_total,population_growth_annual_prcnt,population_in_largest_city
0,1,2020,None,None,None,None,None,2.831514,-0.223584,0.0,0.906299,8602317.0
1,1,1990,None,None,None,None,None,4.008408,1.727181,28118.0,2.185105,3037805.0
2,1,1991,None,None,None,None,None,3.958055,1.670721,0.0,2.138311,3152771.0
3,1,1992,None,None,None,None,None,3.881243,1.594102,0.0,2.070218,3272256.0
4,1,1993,None,None,None,None,None,3.766377,1.485377,0.0,1.968859,3395922.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4831,179,2016,46.316,1.237,156.993,65203.529,61790.329,0.031996,-0.936820,0.0,-0.051137,37326706.0
4832,179,2017,46.721,1.296,164.07,65047.99,61614.482,0.003375,-0.999097,0.0,-0.081874,37397437.0
4833,179,2018,47.139,1.407,177.47,64855.455,61400.411,-0.038428,-1.088373,0.0,-0.126880,37468302.0
4834,179,2019,47.572,1.464,183.953,64633.006,61158.671,-0.051001,-1.123327,0.0,-0.140465,37435191.0
4835,179,2020,47.983,0.7,87.584,64363.155,60881.605,-0.202631,-1.311156,0.0,-0.294195,37393129.0

In [87]:
import etl

In [91]:
etl.country_code_df.cod.sort_values().unique().to_list()

AttributeError: 'numpy.ndarray' object has no attribute 'to_list'

In [92]:
ccdf = etl.country_code_df

In [98]:
ccdf = ccdf.sort_values('cod').reset_index(drop=True)

In [99]:
ccdf.index = np.arange(1, len(ccdf) + 1)

     cod         name   lang
0      1      vietnam     vi
1      2  afghanistan  fa-AF
2      3   bangladesh  bn-BD
3      4       bhutan     dz
4      5        india  en-IN
..   ...          ...    ...
172  173    hong kong  zh-HK
173  174        macao     zh
174  175       taiwan  zh-TW
175  176  north korea    NaN
176  177        japan     ja

[177 rows x 3 columns]