In [178]:
import pandas as pd
import numpy as np
import etl

In [179]:
total_pvp = pd.read_csv('../datasets/processed/proyecto_poblacion/total_pvp.csv')
total_pvp = total_pvp.drop(['Unnamed: 0','Index','Notes of destination','Location code of destination','Type of data of destination','Location code of origin'],axis=1)
total_pvp.columns = ['destination','origin','1990','1995','2000','2005','2010','2015','2020']

In [180]:
total_pvp.destination = total_pvp.destination.apply(etl.remove_special_characters).str.lower()
total_pvp.destination = total_pvp.destination.astype(str)
total_pvp.destination = total_pvp.destination.str.strip()
total_pvp.destination = total_pvp.destination.apply(etl.normalize_country).str.lower()

total_pvp.origin = total_pvp.origin.apply(etl.remove_special_characters).str.lower()
total_pvp.origin = total_pvp.origin.astype(str)
total_pvp.origin = total_pvp.origin.str.strip()
total_pvp.origin = total_pvp.origin.apply(etl.normalize_country).str.lower()

In [181]:
total_pvp = total_pvp.drop(total_pvp.where(~total_pvp.destination.isin(etl.country_code_df['name'])).dropna().index,axis=0)
total_pvp = total_pvp.drop(total_pvp.where(~total_pvp.origin.isin(etl.country_code_df['name'])).dropna().index,axis=0)

In [182]:
total_pvp = total_pvp.rename({'destination':'name'},axis=1)
etl.insert_country_code(total_pvp)

In [184]:
total_pvp = total_pvp.rename({'name':'destination','region_id':'destination_id','origin':'name'},axis=1)

In [186]:
total_pvp = total_pvp.rename({'name':'origin'},axis=1)

In [187]:
total_pvp

,destination,destination_id,origin,1990,1995,2000,2005,2010,2015,2020
6557,burundi,72,belgium,642,621,475,466,497,605,718
6558,burundi,72,congo,36654,41447,37951,99099,147611,175768,199585
6559,burundi,72,france,321,310,237,232,248,302,358
6560,burundi,72,kenya,186,216,202,502,847,1032,1226
6561,burundi,72,rwanda,221943,160197,66415,61104,54794,64363,76567
...,...,...,...,...,...,...,...,...,...,...
8377,congo,114,portugal,442,511,716,455,1084,1441,1431
8378,congo,114,russia,790,913,1280,814,1938,2576,2558
8379,congo,114,rwanda,0,5503,12480,7936,18900,25119,24955
8380,congo,114,senegal,3468,4436,6591,9227,9981,13265,13178
8381,congo,114,togo,747,863,1211,770,1834,2437,2419